# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: INSTANCE-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AreaCreationDTO Class
#'
#' @field uri 
#' @field rdf_type 
#' @field name 
#' @field description 
#' @field geometry 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AreaCreationDTO <- R6::R6Class(
  'AreaCreationDTO',
  public = list(
    `uri` = NULL,
    `rdf_type` = NULL,
    `name` = NULL,
    `description` = NULL,
    `geometry` = NULL,
    initialize = function(`uri`, `rdf_type`, `name`, `description`, `geometry`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`rdf_type`)) {
        stopifnot(is.character(`rdf_type`), length(`rdf_type`) == 1)
        self$`rdf_type` <- `rdf_type`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`geometry`)) {
        stopifnot(R6::is.R6(`geometry`))
        self$`geometry` <- `geometry`
      }
    },
    toJSON = function() {
      AreaCreationDTOObject <- list()
      if (!is.null(self$`uri`)) {
        AreaCreationDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`rdf_type`)) {
        AreaCreationDTOObject[['rdf_type']] <- self$`rdf_type`
      }
      if (!is.null(self$`name`)) {
        AreaCreationDTOObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        AreaCreationDTOObject[['description']] <- self$`description`
      }
      if (!is.null(self$`geometry`)) {
        AreaCreationDTOObject[['geometry']] <- self$`geometry`$toJSON()
      }

      AreaCreationDTOObject
    },
    fromJSON = function(AreaCreationDTOJson) {
      AreaCreationDTOObject <- jsonlite::fromJSON(AreaCreationDTOJson)
      if (!is.null(AreaCreationDTOObject$`uri`)) {
        self$`uri` <- AreaCreationDTOObject$`uri`
      }
      if (!is.null(AreaCreationDTOObject$`rdf_type`)) {
        self$`rdf_type` <- AreaCreationDTOObject$`rdf_type`
      }
      if (!is.null(AreaCreationDTOObject$`name`)) {
        self$`name` <- AreaCreationDTOObject$`name`
      }
      if (!is.null(AreaCreationDTOObject$`description`)) {
        self$`description` <- AreaCreationDTOObject$`description`
      }
      if (!is.null(AreaCreationDTOObject$`geometry`)) {
        geometryObject <- GeoJsonObject$new()
        geometryObject$fromJSON(jsonlite::toJSON(AreaCreationDTOObject$geometry, auto_unbox = TRUE, null = "null"))
        self$`geometry` <- geometryObject
      }
    },
    fromJSONObject = function(AreaCreationDTOObject) {
      if (!is.null(AreaCreationDTOObject$`uri`)) {
        self$`uri` <- AreaCreationDTOObject$`uri`
      }
      if (!is.null(AreaCreationDTOObject$`rdf_type`)) {
        self$`rdf_type` <- AreaCreationDTOObject$`rdf_type`
      }
      if (!is.null(AreaCreationDTOObject$`name`)) {
        self$`name` <- AreaCreationDTOObject$`name`
      }
      if (!is.null(AreaCreationDTOObject$`description`)) {
        self$`description` <- AreaCreationDTOObject$`description`
      }
      if (!is.null(AreaCreationDTOObject$`geometry`)) {
        geometryObject <- GeoJsonObject$new()
        geometryObject$fromJSON(jsonlite::toJSON(AreaCreationDTOObject$geometry, auto_unbox = TRUE, null = "null"))
        self$`geometry` <- geometryObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "rdf_type": %s,
           "name": %s,
           "description": %s,
           "geometry": %s
        }',
        ifelse(is.null(self$`uri`), "null",jsonlite::toJSON(self$`uri`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`rdf_type`), "null",jsonlite::toJSON(self$`rdf_type`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`name`), "null",jsonlite::toJSON(self$`name`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`description`), "null",jsonlite::toJSON(self$`description`,auto_unbox=TRUE, null = "null")),
        jsonlite::toJSON(self$`geometry`$toJSON(),auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(AreaCreationDTOJson) {
      AreaCreationDTOObject <- jsonlite::fromJSON(AreaCreationDTOJson)
      self$`uri` <- AreaCreationDTOObject$`uri`
      self$`rdf_type` <- AreaCreationDTOObject$`rdf_type`
      self$`name` <- AreaCreationDTOObject$`name`
      self$`description` <- AreaCreationDTOObject$`description`
      GeoJsonObjectObject <- GeoJsonObject$new()
      self$`geometry` <- GeoJsonObjectObject$fromJSON(jsonlite::toJSON(AreaCreationDTOObject$geometry, auto_unbox = TRUE))
    }
  )
)
