# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: INSTANCE-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DataCSVValidationModel Class
#'
#' @field missingHeaders 
#' @field invalidHeaderURIs 
#' @field datatypeErrors 
#' @field uriNotFoundErrors 
#' @field invalidURIErrors 
#' @field missingRequiredValueErrors 
#' @field invalidValueErrors 
#' @field alreadyExistingURIErrors 
#' @field duplicateURIErrors 
#' @field invalidObjectErrors 
#' @field invalidDateErrors 
#' @field invalidDataTypeErrors 
#' @field duplicatedDataErrors 
#' @field headers 
#' @field headersLabels 
#' @field nbLinesImported 
#' @field nbLinesToImport 
#' @field validationStep 
#' @field insertionStep 
#' @field validCSV 
#' @field tooLargeDataset 
#' @field errorMessage 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataCSVValidationModel <- R6::R6Class(
  'DataCSVValidationModel',
  public = list(
    `missingHeaders` = NULL,
    `invalidHeaderURIs` = NULL,
    `datatypeErrors` = NULL,
    `uriNotFoundErrors` = NULL,
    `invalidURIErrors` = NULL,
    `missingRequiredValueErrors` = NULL,
    `invalidValueErrors` = NULL,
    `alreadyExistingURIErrors` = NULL,
    `duplicateURIErrors` = NULL,
    `invalidObjectErrors` = NULL,
    `invalidDateErrors` = NULL,
    `invalidDataTypeErrors` = NULL,
    `duplicatedDataErrors` = NULL,
    `headers` = NULL,
    `headersLabels` = NULL,
    `nbLinesImported` = NULL,
    `nbLinesToImport` = NULL,
    `validationStep` = NULL,
    `insertionStep` = NULL,
    `validCSV` = NULL,
    `tooLargeDataset` = NULL,
    `errorMessage` = NULL,
    initialize = function(`missingHeaders`, `invalidHeaderURIs`, `datatypeErrors`, `uriNotFoundErrors`, `invalidURIErrors`, `missingRequiredValueErrors`, `invalidValueErrors`, `alreadyExistingURIErrors`, `duplicateURIErrors`, `invalidObjectErrors`, `invalidDateErrors`, `invalidDataTypeErrors`, `duplicatedDataErrors`, `headers`, `headersLabels`, `nbLinesImported`, `nbLinesToImport`, `validationStep`, `insertionStep`, `validCSV`, `tooLargeDataset`, `errorMessage`){
      if (!missing(`missingHeaders`)) {
        stopifnot(is.list(`missingHeaders`), length(`missingHeaders`) != 0)
        lapply(`missingHeaders`, function(x) stopifnot(is.character(x)))
        self$`missingHeaders` <- `missingHeaders`
      }
      if (!missing(`invalidHeaderURIs`)) {
        self$`invalidHeaderURIs` <- `invalidHeaderURIs`
      }
      if (!missing(`datatypeErrors`)) {
        stopifnot(R6::is.R6(`datatypeErrors`))
        self$`datatypeErrors` <- `datatypeErrors`
      }
      if (!missing(`uriNotFoundErrors`)) {
        stopifnot(R6::is.R6(`uriNotFoundErrors`))
        self$`uriNotFoundErrors` <- `uriNotFoundErrors`
      }
      if (!missing(`invalidURIErrors`)) {
        stopifnot(R6::is.R6(`invalidURIErrors`))
        self$`invalidURIErrors` <- `invalidURIErrors`
      }
      if (!missing(`missingRequiredValueErrors`)) {
        stopifnot(R6::is.R6(`missingRequiredValueErrors`))
        self$`missingRequiredValueErrors` <- `missingRequiredValueErrors`
      }
      if (!missing(`invalidValueErrors`)) {
        stopifnot(R6::is.R6(`invalidValueErrors`))
        self$`invalidValueErrors` <- `invalidValueErrors`
      }
      if (!missing(`alreadyExistingURIErrors`)) {
        stopifnot(R6::is.R6(`alreadyExistingURIErrors`))
        self$`alreadyExistingURIErrors` <- `alreadyExistingURIErrors`
      }
      if (!missing(`duplicateURIErrors`)) {
        stopifnot(R6::is.R6(`duplicateURIErrors`))
        self$`duplicateURIErrors` <- `duplicateURIErrors`
      }
      if (!missing(`invalidObjectErrors`)) {
        stopifnot(R6::is.R6(`invalidObjectErrors`))
        self$`invalidObjectErrors` <- `invalidObjectErrors`
      }
      if (!missing(`invalidDateErrors`)) {
        stopifnot(R6::is.R6(`invalidDateErrors`))
        self$`invalidDateErrors` <- `invalidDateErrors`
      }
      if (!missing(`invalidDataTypeErrors`)) {
        stopifnot(R6::is.R6(`invalidDataTypeErrors`))
        self$`invalidDataTypeErrors` <- `invalidDataTypeErrors`
      }
      if (!missing(`duplicatedDataErrors`)) {
        stopifnot(R6::is.R6(`duplicatedDataErrors`))
        self$`duplicatedDataErrors` <- `duplicatedDataErrors`
      }
      if (!missing(`headers`)) {
        stopifnot(is.list(`headers`), length(`headers`) != 0)
        lapply(`headers`, function(x) stopifnot(is.character(x)))
        self$`headers` <- `headers`
      }
      if (!missing(`headersLabels`)) {
        stopifnot(is.list(`headersLabels`), length(`headersLabels`) != 0)
        lapply(`headersLabels`, function(x) stopifnot(is.character(x)))
        self$`headersLabels` <- `headersLabels`
      }
      if (!missing(`nbLinesImported`)) {
        stopifnot(is.numeric(`nbLinesImported`), length(`nbLinesImported`) == 1)
        self$`nbLinesImported` <- `nbLinesImported`
      }
      if (!missing(`nbLinesToImport`)) {
        stopifnot(is.numeric(`nbLinesToImport`), length(`nbLinesToImport`) == 1)
        self$`nbLinesToImport` <- `nbLinesToImport`
      }
      if (!missing(`validationStep`)) {
        self$`validationStep` <- `validationStep`
      }
      if (!missing(`insertionStep`)) {
        self$`insertionStep` <- `insertionStep`
      }
      if (!missing(`validCSV`)) {
        self$`validCSV` <- `validCSV`
      }
      if (!missing(`tooLargeDataset`)) {
        self$`tooLargeDataset` <- `tooLargeDataset`
      }
      if (!missing(`errorMessage`)) {
        stopifnot(is.character(`errorMessage`), length(`errorMessage`) == 1)
        self$`errorMessage` <- `errorMessage`
      }
    },
    toJSON = function() {
      DataCSVValidationModelObject <- list()
      if (!is.null(self$`missingHeaders`)) {
        DataCSVValidationModelObject[['missingHeaders']] <- self$`missingHeaders`
      }
      if (!is.null(self$`invalidHeaderURIs`)) {
        DataCSVValidationModelObject[['invalidHeaderURIs']] <- self$`invalidHeaderURIs`
      }
      if (!is.null(self$`datatypeErrors`)) {
        DataCSVValidationModelObject[['datatypeErrors']] <- self$`datatypeErrors`$toJSON()
      }
      if (!is.null(self$`uriNotFoundErrors`)) {
        DataCSVValidationModelObject[['uriNotFoundErrors']] <- self$`uriNotFoundErrors`$toJSON()
      }
      if (!is.null(self$`invalidURIErrors`)) {
        DataCSVValidationModelObject[['invalidURIErrors']] <- self$`invalidURIErrors`$toJSON()
      }
      if (!is.null(self$`missingRequiredValueErrors`)) {
        DataCSVValidationModelObject[['missingRequiredValueErrors']] <- self$`missingRequiredValueErrors`$toJSON()
      }
      if (!is.null(self$`invalidValueErrors`)) {
        DataCSVValidationModelObject[['invalidValueErrors']] <- self$`invalidValueErrors`$toJSON()
      }
      if (!is.null(self$`alreadyExistingURIErrors`)) {
        DataCSVValidationModelObject[['alreadyExistingURIErrors']] <- self$`alreadyExistingURIErrors`$toJSON()
      }
      if (!is.null(self$`duplicateURIErrors`)) {
        DataCSVValidationModelObject[['duplicateURIErrors']] <- self$`duplicateURIErrors`$toJSON()
      }
      if (!is.null(self$`invalidObjectErrors`)) {
        DataCSVValidationModelObject[['invalidObjectErrors']] <- self$`invalidObjectErrors`$toJSON()
      }
      if (!is.null(self$`invalidDateErrors`)) {
        DataCSVValidationModelObject[['invalidDateErrors']] <- self$`invalidDateErrors`$toJSON()
      }
      if (!is.null(self$`invalidDataTypeErrors`)) {
        DataCSVValidationModelObject[['invalidDataTypeErrors']] <- self$`invalidDataTypeErrors`$toJSON()
      }
      if (!is.null(self$`duplicatedDataErrors`)) {
        DataCSVValidationModelObject[['duplicatedDataErrors']] <- self$`duplicatedDataErrors`$toJSON()
      }
      if (!is.null(self$`headers`)) {
        DataCSVValidationModelObject[['headers']] <- self$`headers`
      }
      if (!is.null(self$`headersLabels`)) {
        DataCSVValidationModelObject[['headersLabels']] <- self$`headersLabels`
      }
      if (!is.null(self$`nbLinesImported`)) {
        DataCSVValidationModelObject[['nbLinesImported']] <- self$`nbLinesImported`
      }
      if (!is.null(self$`nbLinesToImport`)) {
        DataCSVValidationModelObject[['nbLinesToImport']] <- self$`nbLinesToImport`
      }
      if (!is.null(self$`validationStep`)) {
        DataCSVValidationModelObject[['validationStep']] <- self$`validationStep`
      }
      if (!is.null(self$`insertionStep`)) {
        DataCSVValidationModelObject[['insertionStep']] <- self$`insertionStep`
      }
      if (!is.null(self$`validCSV`)) {
        DataCSVValidationModelObject[['validCSV']] <- self$`validCSV`
      }
      if (!is.null(self$`tooLargeDataset`)) {
        DataCSVValidationModelObject[['tooLargeDataset']] <- self$`tooLargeDataset`
      }
      if (!is.null(self$`errorMessage`)) {
        DataCSVValidationModelObject[['errorMessage']] <- self$`errorMessage`
      }

      DataCSVValidationModelObject
    },
    fromJSON = function(DataCSVValidationModelJson) {
      DataCSVValidationModelObject <- jsonlite::fromJSON(DataCSVValidationModelJson)
      if (!is.null(DataCSVValidationModelObject$`missingHeaders`)) {
        self$`missingHeaders` <- DataCSVValidationModelObject$`missingHeaders`
      }
      if (!is.null(DataCSVValidationModelObject$`invalidHeaderURIs`)) {
        self$`invalidHeaderURIs` <- DataCSVValidationModelObject$`invalidHeaderURIs`
      }
      if (!is.null(DataCSVValidationModelObject$`datatypeErrors`)) {
        datatypeErrorsObject <- CSVDatatypeError$new()
        datatypeErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$datatypeErrors, auto_unbox = TRUE, null = "null"))
        self$`datatypeErrors` <- datatypeErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`uriNotFoundErrors`)) {
        uriNotFoundErrorsObject <- CSVURINotFoundError$new()
        uriNotFoundErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$uriNotFoundErrors, auto_unbox = TRUE, null = "null"))
        self$`uriNotFoundErrors` <- uriNotFoundErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidURIErrors`)) {
        invalidURIErrorsObject <- CSVCell$new()
        invalidURIErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidURIErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidURIErrors` <- invalidURIErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`missingRequiredValueErrors`)) {
        missingRequiredValueErrorsObject <- CSVCell$new()
        missingRequiredValueErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$missingRequiredValueErrors, auto_unbox = TRUE, null = "null"))
        self$`missingRequiredValueErrors` <- missingRequiredValueErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidValueErrors`)) {
        invalidValueErrorsObject <- CSVCell$new()
        invalidValueErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidValueErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidValueErrors` <- invalidValueErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`alreadyExistingURIErrors`)) {
        alreadyExistingURIErrorsObject <- CSVCell$new()
        alreadyExistingURIErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$alreadyExistingURIErrors, auto_unbox = TRUE, null = "null"))
        self$`alreadyExistingURIErrors` <- alreadyExistingURIErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`duplicateURIErrors`)) {
        duplicateURIErrorsObject <- CSVDuplicateURIError$new()
        duplicateURIErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$duplicateURIErrors, auto_unbox = TRUE, null = "null"))
        self$`duplicateURIErrors` <- duplicateURIErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidObjectErrors`)) {
        invalidObjectErrorsObject <- CSVCell$new()
        invalidObjectErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidObjectErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidObjectErrors` <- invalidObjectErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidDateErrors`)) {
        invalidDateErrorsObject <- CSVCell$new()
        invalidDateErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidDateErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidDateErrors` <- invalidDateErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidDataTypeErrors`)) {
        invalidDataTypeErrorsObject <- CSVCell$new()
        invalidDataTypeErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidDataTypeErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidDataTypeErrors` <- invalidDataTypeErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`duplicatedDataErrors`)) {
        duplicatedDataErrorsObject <- CSVCell$new()
        duplicatedDataErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$duplicatedDataErrors, auto_unbox = TRUE, null = "null"))
        self$`duplicatedDataErrors` <- duplicatedDataErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`headers`)) {
        self$`headers` <- DataCSVValidationModelObject$`headers`
      }
      if (!is.null(DataCSVValidationModelObject$`headersLabels`)) {
        self$`headersLabels` <- DataCSVValidationModelObject$`headersLabels`
      }
      if (!is.null(DataCSVValidationModelObject$`nbLinesImported`)) {
        self$`nbLinesImported` <- DataCSVValidationModelObject$`nbLinesImported`
      }
      if (!is.null(DataCSVValidationModelObject$`nbLinesToImport`)) {
        self$`nbLinesToImport` <- DataCSVValidationModelObject$`nbLinesToImport`
      }
      if (!is.null(DataCSVValidationModelObject$`validationStep`)) {
        self$`validationStep` <- DataCSVValidationModelObject$`validationStep`
      }
      if (!is.null(DataCSVValidationModelObject$`insertionStep`)) {
        self$`insertionStep` <- DataCSVValidationModelObject$`insertionStep`
      }
      if (!is.null(DataCSVValidationModelObject$`validCSV`)) {
        self$`validCSV` <- DataCSVValidationModelObject$`validCSV`
      }
      if (!is.null(DataCSVValidationModelObject$`tooLargeDataset`)) {
        self$`tooLargeDataset` <- DataCSVValidationModelObject$`tooLargeDataset`
      }
      if (!is.null(DataCSVValidationModelObject$`errorMessage`)) {
        self$`errorMessage` <- DataCSVValidationModelObject$`errorMessage`
      }
    },
    fromJSONObject = function(DataCSVValidationModelObject) {
      if (!is.null(DataCSVValidationModelObject$`missingHeaders`)) {
        self$`missingHeaders` <- DataCSVValidationModelObject$`missingHeaders`
      }
      if (!is.null(DataCSVValidationModelObject$`invalidHeaderURIs`)) {
        self$`invalidHeaderURIs` <- DataCSVValidationModelObject$`invalidHeaderURIs`
      }
      if (!is.null(DataCSVValidationModelObject$`datatypeErrors`)) {
        datatypeErrorsObject <- CSVDatatypeError$new()
        datatypeErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$datatypeErrors, auto_unbox = TRUE, null = "null"))
        self$`datatypeErrors` <- datatypeErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`uriNotFoundErrors`)) {
        uriNotFoundErrorsObject <- CSVURINotFoundError$new()
        uriNotFoundErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$uriNotFoundErrors, auto_unbox = TRUE, null = "null"))
        self$`uriNotFoundErrors` <- uriNotFoundErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidURIErrors`)) {
        invalidURIErrorsObject <- CSVCell$new()
        invalidURIErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidURIErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidURIErrors` <- invalidURIErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`missingRequiredValueErrors`)) {
        missingRequiredValueErrorsObject <- CSVCell$new()
        missingRequiredValueErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$missingRequiredValueErrors, auto_unbox = TRUE, null = "null"))
        self$`missingRequiredValueErrors` <- missingRequiredValueErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidValueErrors`)) {
        invalidValueErrorsObject <- CSVCell$new()
        invalidValueErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidValueErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidValueErrors` <- invalidValueErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`alreadyExistingURIErrors`)) {
        alreadyExistingURIErrorsObject <- CSVCell$new()
        alreadyExistingURIErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$alreadyExistingURIErrors, auto_unbox = TRUE, null = "null"))
        self$`alreadyExistingURIErrors` <- alreadyExistingURIErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`duplicateURIErrors`)) {
        duplicateURIErrorsObject <- CSVDuplicateURIError$new()
        duplicateURIErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$duplicateURIErrors, auto_unbox = TRUE, null = "null"))
        self$`duplicateURIErrors` <- duplicateURIErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidObjectErrors`)) {
        invalidObjectErrorsObject <- CSVCell$new()
        invalidObjectErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidObjectErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidObjectErrors` <- invalidObjectErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidDateErrors`)) {
        invalidDateErrorsObject <- CSVCell$new()
        invalidDateErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidDateErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidDateErrors` <- invalidDateErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`invalidDataTypeErrors`)) {
        invalidDataTypeErrorsObject <- CSVCell$new()
        invalidDataTypeErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidDataTypeErrors, auto_unbox = TRUE, null = "null"))
        self$`invalidDataTypeErrors` <- invalidDataTypeErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`duplicatedDataErrors`)) {
        duplicatedDataErrorsObject <- CSVCell$new()
        duplicatedDataErrorsObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$duplicatedDataErrors, auto_unbox = TRUE, null = "null"))
        self$`duplicatedDataErrors` <- duplicatedDataErrorsObject
      }
      if (!is.null(DataCSVValidationModelObject$`headers`)) {
        self$`headers` <- DataCSVValidationModelObject$`headers`
      }
      if (!is.null(DataCSVValidationModelObject$`headersLabels`)) {
        self$`headersLabels` <- DataCSVValidationModelObject$`headersLabels`
      }
      if (!is.null(DataCSVValidationModelObject$`nbLinesImported`)) {
        self$`nbLinesImported` <- DataCSVValidationModelObject$`nbLinesImported`
      }
      if (!is.null(DataCSVValidationModelObject$`nbLinesToImport`)) {
        self$`nbLinesToImport` <- DataCSVValidationModelObject$`nbLinesToImport`
      }
      if (!is.null(DataCSVValidationModelObject$`validationStep`)) {
        self$`validationStep` <- DataCSVValidationModelObject$`validationStep`
      }
      if (!is.null(DataCSVValidationModelObject$`insertionStep`)) {
        self$`insertionStep` <- DataCSVValidationModelObject$`insertionStep`
      }
      if (!is.null(DataCSVValidationModelObject$`validCSV`)) {
        self$`validCSV` <- DataCSVValidationModelObject$`validCSV`
      }
      if (!is.null(DataCSVValidationModelObject$`tooLargeDataset`)) {
        self$`tooLargeDataset` <- DataCSVValidationModelObject$`tooLargeDataset`
      }
      if (!is.null(DataCSVValidationModelObject$`errorMessage`)) {
        self$`errorMessage` <- DataCSVValidationModelObject$`errorMessage`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "missingHeaders": [%s],
           "invalidHeaderURIs": %s,
           "datatypeErrors": %s,
           "uriNotFoundErrors": %s,
           "invalidURIErrors": %s,
           "missingRequiredValueErrors": %s,
           "invalidValueErrors": %s,
           "alreadyExistingURIErrors": %s,
           "duplicateURIErrors": %s,
           "invalidObjectErrors": %s,
           "invalidDateErrors": %s,
           "invalidDataTypeErrors": %s,
           "duplicatedDataErrors": %s,
           "headers": [%s],
           "headersLabels": [%s],
           "nbLinesImported": %d,
           "nbLinesToImport": %d,
           "validationStep": %s,
           "insertionStep": %s,
           "validCSV": %s,
           "tooLargeDataset": %s,
           "errorMessage": %s
        }',
        lapply(self$`missingHeaders`, function(x) paste(paste0('"', x, '"'), sep=",")),
        jsonlite::toJSON(self$`invalidHeaderURIs`,auto_unbox=TRUE, null = "null"),
        self$`datatypeErrors`$toJSON(),
        self$`uriNotFoundErrors`$toJSON(),
        self$`invalidURIErrors`$toJSON(),
        self$`missingRequiredValueErrors`$toJSON(),
        self$`invalidValueErrors`$toJSON(),
        self$`alreadyExistingURIErrors`$toJSON(),
        self$`duplicateURIErrors`$toJSON(),
        self$`invalidObjectErrors`$toJSON(),
        self$`invalidDateErrors`$toJSON(),
        self$`invalidDataTypeErrors`$toJSON(),
        self$`duplicatedDataErrors`$toJSON(),
        lapply(self$`headers`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`headersLabels`, function(x) paste(paste0('"', x, '"'), sep=",")),
        jsonlite::toJSON(self$`nbLinesImported`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`nbLinesToImport`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`validationStep`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`insertionStep`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`validCSV`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`tooLargeDataset`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`errorMessage`,auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(DataCSVValidationModelJson) {
      DataCSVValidationModelObject <- jsonlite::fromJSON(DataCSVValidationModelJson)
      self$`missingHeaders` <- DataCSVValidationModelObject$`missingHeaders`
      self$`invalidHeaderURIs` <- DataCSVValidationModelObject$`invalidHeaderURIs`
      CSVDatatypeErrorObject <- CSVDatatypeError$new()
      self$`datatypeErrors` <- CSVDatatypeErrorObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$datatypeErrors, auto_unbox = TRUE))
      CSVURINotFoundErrorObject <- CSVURINotFoundError$new()
      self$`uriNotFoundErrors` <- CSVURINotFoundErrorObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$uriNotFoundErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`invalidURIErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidURIErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`missingRequiredValueErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$missingRequiredValueErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`invalidValueErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidValueErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`alreadyExistingURIErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$alreadyExistingURIErrors, auto_unbox = TRUE))
      CSVDuplicateURIErrorObject <- CSVDuplicateURIError$new()
      self$`duplicateURIErrors` <- CSVDuplicateURIErrorObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$duplicateURIErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`invalidObjectErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidObjectErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`invalidDateErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidDateErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`invalidDataTypeErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$invalidDataTypeErrors, auto_unbox = TRUE))
      CSVCellObject <- CSVCell$new()
      self$`duplicatedDataErrors` <- CSVCellObject$fromJSON(jsonlite::toJSON(DataCSVValidationModelObject$duplicatedDataErrors, auto_unbox = TRUE))
      self$`headers` <- DataCSVValidationModelObject$`headers`
      self$`headersLabels` <- DataCSVValidationModelObject$`headersLabels`
      self$`nbLinesImported` <- DataCSVValidationModelObject$`nbLinesImported`
      self$`nbLinesToImport` <- DataCSVValidationModelObject$`nbLinesToImport`
      self$`validationStep` <- DataCSVValidationModelObject$`validationStep`
      self$`insertionStep` <- DataCSVValidationModelObject$`insertionStep`
      self$`validCSV` <- DataCSVValidationModelObject$`validCSV`
      self$`tooLargeDataset` <- DataCSVValidationModelObject$`tooLargeDataset`
      self$`errorMessage` <- DataCSVValidationModelObject$`errorMessage`
    }
  )
)
