# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0.0-rc+2
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ErrorResponse Class
#'
#' @field metadata 
#' @field result 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ErrorResponse <- R6::R6Class(
  'ErrorResponse',
  public = list(
    `metadata` = NULL,
    `result` = NULL,
    initialize = function(`metadata`, `result`){
      if (!missing(`metadata`)) {
        stopifnot(R6::is.R6(`metadata`))
        self$`metadata` <- `metadata`
      }
      if (!missing(`result`)) {
        stopifnot(R6::is.R6(`result`))
        self$`result` <- `result`
      }
    },
    toJSON = function() {
      ErrorResponseObject <- list()
      if (!is.null(self$`metadata`)) {
        ErrorResponseObject[['metadata']] <- self$`metadata`$toJSON()
      }
      if (!is.null(self$`result`)) {
        ErrorResponseObject[['result']] <- self$`result`$toJSON()
      }

      ErrorResponseObject
    },
    fromJSON = function(ErrorResponseJson) {
      ErrorResponseObject <- jsonlite::fromJSON(ErrorResponseJson)
      if (!is.null(ErrorResponseObject$`metadata`)) {
        metadataObject <- MetadataDTO$new()
        metadataObject$fromJSON(jsonlite::toJSON(ErrorResponseObject$metadata, auto_unbox = TRUE, null = "null"))
        self$`metadata` <- metadataObject
      }
      if (!is.null(ErrorResponseObject$`result`)) {
        resultObject <- ErrorDTO$new()
        resultObject$fromJSON(jsonlite::toJSON(ErrorResponseObject$result, auto_unbox = TRUE, null = "null"))
        self$`result` <- resultObject
      }
    },
    fromJSONObject = function(ErrorResponseObject) {
      if (!is.null(ErrorResponseObject$`metadata`)) {
        metadataObject <- MetadataDTO$new()
        metadataObject$fromJSON(jsonlite::toJSON(ErrorResponseObject$metadata, auto_unbox = TRUE, null = "null"))
        self$`metadata` <- metadataObject
      }
      if (!is.null(ErrorResponseObject$`result`)) {
        resultObject <- ErrorDTO$new()
        resultObject$fromJSON(jsonlite::toJSON(ErrorResponseObject$result, auto_unbox = TRUE, null = "null"))
        self$`result` <- resultObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "metadata": %s,
           "result": %s
        }',
        jsonlite::toJSON(self$`metadata`$toJSON(),auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`result`$toJSON(),auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(ErrorResponseJson) {
      ErrorResponseObject <- jsonlite::fromJSON(ErrorResponseJson)
      MetadataDTOObject <- MetadataDTO$new()
      self$`metadata` <- MetadataDTOObject$fromJSON(jsonlite::toJSON(ErrorResponseObject$metadata, auto_unbox = TRUE))
      ErrorDTOObject <- ErrorDTO$new()
      self$`result` <- ErrorDTOObject$fromJSON(jsonlite::toJSON(ErrorResponseObject$result, auto_unbox = TRUE))
    }
  )
)
