# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: INSTANCE-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InfrastructureCreationDTO Class
#'
#' @field uri 
#' @field rdf_type 
#' @field rdf_type_name 
#' @field name 
#' @field parent 
#' @field children 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InfrastructureCreationDTO <- R6::R6Class(
  'InfrastructureCreationDTO',
  public = list(
    `uri` = NULL,
    `rdf_type` = NULL,
    `rdf_type_name` = NULL,
    `name` = NULL,
    `parent` = NULL,
    `children` = NULL,
    initialize = function(`uri`, `rdf_type`, `rdf_type_name`, `name`, `parent`, `children`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`rdf_type`)) {
        stopifnot(is.character(`rdf_type`), length(`rdf_type`) == 1)
        self$`rdf_type` <- `rdf_type`
      }
      if (!missing(`rdf_type_name`)) {
        stopifnot(is.character(`rdf_type_name`), length(`rdf_type_name`) == 1)
        self$`rdf_type_name` <- `rdf_type_name`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`parent`)) {
        stopifnot(is.character(`parent`), length(`parent`) == 1)
        self$`parent` <- `parent`
      }
      if (!missing(`children`)) {
        stopifnot(is.list(`children`), length(`children`) != 0)
        lapply(`children`, function(x) stopifnot(is.character(x)))
        self$`children` <- `children`
      }
    },
    toJSON = function() {
      InfrastructureCreationDTOObject <- list()
      if (!is.null(self$`uri`)) {
        InfrastructureCreationDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`rdf_type`)) {
        InfrastructureCreationDTOObject[['rdf_type']] <- self$`rdf_type`
      }
      if (!is.null(self$`rdf_type_name`)) {
        InfrastructureCreationDTOObject[['rdf_type_name']] <- self$`rdf_type_name`
      }
      if (!is.null(self$`name`)) {
        InfrastructureCreationDTOObject[['name']] <- self$`name`
      }
      if (!is.null(self$`parent`)) {
        InfrastructureCreationDTOObject[['parent']] <- self$`parent`
      }
      if (!is.null(self$`children`)) {
        InfrastructureCreationDTOObject[['children']] <- self$`children`
      }

      InfrastructureCreationDTOObject
    },
    fromJSON = function(InfrastructureCreationDTOJson) {
      InfrastructureCreationDTOObject <- jsonlite::fromJSON(InfrastructureCreationDTOJson)
      if (!is.null(InfrastructureCreationDTOObject$`uri`)) {
        self$`uri` <- InfrastructureCreationDTOObject$`uri`
      }
      if (!is.null(InfrastructureCreationDTOObject$`rdf_type`)) {
        self$`rdf_type` <- InfrastructureCreationDTOObject$`rdf_type`
      }
      if (!is.null(InfrastructureCreationDTOObject$`rdf_type_name`)) {
        self$`rdf_type_name` <- InfrastructureCreationDTOObject$`rdf_type_name`
      }
      if (!is.null(InfrastructureCreationDTOObject$`name`)) {
        self$`name` <- InfrastructureCreationDTOObject$`name`
      }
      if (!is.null(InfrastructureCreationDTOObject$`parent`)) {
        self$`parent` <- InfrastructureCreationDTOObject$`parent`
      }
      if (!is.null(InfrastructureCreationDTOObject$`children`)) {
        self$`children` <- InfrastructureCreationDTOObject$`children`
      }
    },
    fromJSONObject = function(InfrastructureCreationDTOObject) {
      if (!is.null(InfrastructureCreationDTOObject$`uri`)) {
        self$`uri` <- InfrastructureCreationDTOObject$`uri`
      }
      if (!is.null(InfrastructureCreationDTOObject$`rdf_type`)) {
        self$`rdf_type` <- InfrastructureCreationDTOObject$`rdf_type`
      }
      if (!is.null(InfrastructureCreationDTOObject$`rdf_type_name`)) {
        self$`rdf_type_name` <- InfrastructureCreationDTOObject$`rdf_type_name`
      }
      if (!is.null(InfrastructureCreationDTOObject$`name`)) {
        self$`name` <- InfrastructureCreationDTOObject$`name`
      }
      if (!is.null(InfrastructureCreationDTOObject$`parent`)) {
        self$`parent` <- InfrastructureCreationDTOObject$`parent`
      }
      if (!is.null(InfrastructureCreationDTOObject$`children`)) {
        self$`children` <- InfrastructureCreationDTOObject$`children`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "rdf_type": %s,
           "rdf_type_name": %s,
           "name": %s,
           "parent": %s,
           "children": [%s]
        }',
        ifelse(is.null(self$`uri`), "null",jsonlite::toJSON(self$`uri`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`rdf_type`), "null",jsonlite::toJSON(self$`rdf_type`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`rdf_type_name`), "null",jsonlite::toJSON(self$`rdf_type_name`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`name`), "null",jsonlite::toJSON(self$`name`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`parent`), "null",jsonlite::toJSON(self$`parent`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`children`) || length(self$`children`) == 0, "" ,lapply(self$`children`, function(x) paste(paste0('"', x, '"'), sep=",")))
      )
    },
    fromJSONString = function(InfrastructureCreationDTOJson) {
      InfrastructureCreationDTOObject <- jsonlite::fromJSON(InfrastructureCreationDTOJson)
      self$`uri` <- InfrastructureCreationDTOObject$`uri`
      self$`rdf_type` <- InfrastructureCreationDTOObject$`rdf_type`
      self$`rdf_type_name` <- InfrastructureCreationDTOObject$`rdf_type_name`
      self$`name` <- InfrastructureCreationDTOObject$`name`
      self$`parent` <- InfrastructureCreationDTOObject$`parent`
      self$`children` <- InfrastructureCreationDTOObject$`children`
    }
  )
)
