# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: INSTANCE-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InfrastructureFacilityGetDTO Class
#'
#' @field uri 
#' @field rdf_type 
#' @field rdf_type_name 
#' @field name 
#' @field organisation 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InfrastructureFacilityGetDTO <- R6::R6Class(
  'InfrastructureFacilityGetDTO',
  public = list(
    `uri` = NULL,
    `rdf_type` = NULL,
    `rdf_type_name` = NULL,
    `name` = NULL,
    `organisation` = NULL,
    initialize = function(`uri`, `rdf_type`, `rdf_type_name`, `name`, `organisation`){
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!missing(`rdf_type`)) {
        stopifnot(is.character(`rdf_type`), length(`rdf_type`) == 1)
        self$`rdf_type` <- `rdf_type`
      }
      if (!missing(`rdf_type_name`)) {
        stopifnot(is.character(`rdf_type_name`), length(`rdf_type_name`) == 1)
        self$`rdf_type_name` <- `rdf_type_name`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`organisation`)) {
        stopifnot(is.character(`organisation`), length(`organisation`) == 1)
        self$`organisation` <- `organisation`
      }
    },
    toJSON = function() {
      InfrastructureFacilityGetDTOObject <- list()
      if (!is.null(self$`uri`)) {
        InfrastructureFacilityGetDTOObject[['uri']] <- self$`uri`
      }
      if (!is.null(self$`rdf_type`)) {
        InfrastructureFacilityGetDTOObject[['rdf_type']] <- self$`rdf_type`
      }
      if (!is.null(self$`rdf_type_name`)) {
        InfrastructureFacilityGetDTOObject[['rdf_type_name']] <- self$`rdf_type_name`
      }
      if (!is.null(self$`name`)) {
        InfrastructureFacilityGetDTOObject[['name']] <- self$`name`
      }
      if (!is.null(self$`organisation`)) {
        InfrastructureFacilityGetDTOObject[['organisation']] <- self$`organisation`
      }

      InfrastructureFacilityGetDTOObject
    },
    fromJSON = function(InfrastructureFacilityGetDTOJson) {
      InfrastructureFacilityGetDTOObject <- jsonlite::fromJSON(InfrastructureFacilityGetDTOJson)
      if (!is.null(InfrastructureFacilityGetDTOObject$`uri`)) {
        self$`uri` <- InfrastructureFacilityGetDTOObject$`uri`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`rdf_type`)) {
        self$`rdf_type` <- InfrastructureFacilityGetDTOObject$`rdf_type`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`rdf_type_name`)) {
        self$`rdf_type_name` <- InfrastructureFacilityGetDTOObject$`rdf_type_name`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`name`)) {
        self$`name` <- InfrastructureFacilityGetDTOObject$`name`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`organisation`)) {
        self$`organisation` <- InfrastructureFacilityGetDTOObject$`organisation`
      }
    },
    fromJSONObject = function(InfrastructureFacilityGetDTOObject) {
      if (!is.null(InfrastructureFacilityGetDTOObject$`uri`)) {
        self$`uri` <- InfrastructureFacilityGetDTOObject$`uri`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`rdf_type`)) {
        self$`rdf_type` <- InfrastructureFacilityGetDTOObject$`rdf_type`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`rdf_type_name`)) {
        self$`rdf_type_name` <- InfrastructureFacilityGetDTOObject$`rdf_type_name`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`name`)) {
        self$`name` <- InfrastructureFacilityGetDTOObject$`name`
      }
      if (!is.null(InfrastructureFacilityGetDTOObject$`organisation`)) {
        self$`organisation` <- InfrastructureFacilityGetDTOObject$`organisation`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "uri": %s,
           "rdf_type": %s,
           "rdf_type_name": %s,
           "name": %s,
           "organisation": %s
        }',
        jsonlite::toJSON(self$`uri`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`rdf_type`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`rdf_type_name`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`name`,auto_unbox=TRUE, null = "null"),
        jsonlite::toJSON(self$`organisation`,auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(InfrastructureFacilityGetDTOJson) {
      InfrastructureFacilityGetDTOObject <- jsonlite::fromJSON(InfrastructureFacilityGetDTOJson)
      self$`uri` <- InfrastructureFacilityGetDTOObject$`uri`
      self$`rdf_type` <- InfrastructureFacilityGetDTOObject$`rdf_type`
      self$`rdf_type_name` <- InfrastructureFacilityGetDTOObject$`rdf_type_name`
      self$`name` <- InfrastructureFacilityGetDTOObject$`name`
      self$`organisation` <- InfrastructureFacilityGetDTOObject$`organisation`
    }
  )
)
