# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: INSTANCE-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ObservationSummary Class
#'
#' @field collector 
#' @field observationDbId 
#' @field observationTimeStamp 
#' @field observationVariableDbId 
#' @field observationVariableName 
#' @field season 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ObservationSummary <- R6::R6Class(
  'ObservationSummary',
  public = list(
    `collector` = NULL,
    `observationDbId` = NULL,
    `observationTimeStamp` = NULL,
    `observationVariableDbId` = NULL,
    `observationVariableName` = NULL,
    `season` = NULL,
    initialize = function(`collector`, `observationDbId`, `observationTimeStamp`, `observationVariableDbId`, `observationVariableName`, `season`){
      if (!missing(`collector`)) {
        stopifnot(is.character(`collector`), length(`collector`) == 1)
        self$`collector` <- `collector`
      }
      if (!missing(`observationDbId`)) {
        stopifnot(is.character(`observationDbId`), length(`observationDbId`) == 1)
        self$`observationDbId` <- `observationDbId`
      }
      if (!missing(`observationTimeStamp`)) {
        stopifnot(is.character(`observationTimeStamp`), length(`observationTimeStamp`) == 1)
        self$`observationTimeStamp` <- `observationTimeStamp`
      }
      if (!missing(`observationVariableDbId`)) {
        stopifnot(is.character(`observationVariableDbId`), length(`observationVariableDbId`) == 1)
        self$`observationVariableDbId` <- `observationVariableDbId`
      }
      if (!missing(`observationVariableName`)) {
        stopifnot(is.character(`observationVariableName`), length(`observationVariableName`) == 1)
        self$`observationVariableName` <- `observationVariableName`
      }
      if (!missing(`season`)) {
        stopifnot(R6::is.R6(`season`))
        self$`season` <- `season`
      }
    },
    toJSON = function() {
      ObservationSummaryObject <- list()
      if (!is.null(self$`collector`)) {
        ObservationSummaryObject[['collector']] <- self$`collector`
      }
      if (!is.null(self$`observationDbId`)) {
        ObservationSummaryObject[['observationDbId']] <- self$`observationDbId`
      }
      if (!is.null(self$`observationTimeStamp`)) {
        ObservationSummaryObject[['observationTimeStamp']] <- self$`observationTimeStamp`
      }
      if (!is.null(self$`observationVariableDbId`)) {
        ObservationSummaryObject[['observationVariableDbId']] <- self$`observationVariableDbId`
      }
      if (!is.null(self$`observationVariableName`)) {
        ObservationSummaryObject[['observationVariableName']] <- self$`observationVariableName`
      }
      if (!is.null(self$`season`)) {
        ObservationSummaryObject[['season']] <- self$`season`$toJSON()
      }

      ObservationSummaryObject
    },
    fromJSON = function(ObservationSummaryJson) {
      ObservationSummaryObject <- jsonlite::fromJSON(ObservationSummaryJson)
      if (!is.null(ObservationSummaryObject$`collector`)) {
        self$`collector` <- ObservationSummaryObject$`collector`
      }
      if (!is.null(ObservationSummaryObject$`observationDbId`)) {
        self$`observationDbId` <- ObservationSummaryObject$`observationDbId`
      }
      if (!is.null(ObservationSummaryObject$`observationTimeStamp`)) {
        self$`observationTimeStamp` <- ObservationSummaryObject$`observationTimeStamp`
      }
      if (!is.null(ObservationSummaryObject$`observationVariableDbId`)) {
        self$`observationVariableDbId` <- ObservationSummaryObject$`observationVariableDbId`
      }
      if (!is.null(ObservationSummaryObject$`observationVariableName`)) {
        self$`observationVariableName` <- ObservationSummaryObject$`observationVariableName`
      }
      if (!is.null(ObservationSummaryObject$`season`)) {
        seasonObject <- Season$new()
        seasonObject$fromJSON(jsonlite::toJSON(ObservationSummaryObject$season, auto_unbox = TRUE, null = "null"))
        self$`season` <- seasonObject
      }
    },
    fromJSONObject = function(ObservationSummaryObject) {
      if (!is.null(ObservationSummaryObject$`collector`)) {
        self$`collector` <- ObservationSummaryObject$`collector`
      }
      if (!is.null(ObservationSummaryObject$`observationDbId`)) {
        self$`observationDbId` <- ObservationSummaryObject$`observationDbId`
      }
      if (!is.null(ObservationSummaryObject$`observationTimeStamp`)) {
        self$`observationTimeStamp` <- ObservationSummaryObject$`observationTimeStamp`
      }
      if (!is.null(ObservationSummaryObject$`observationVariableDbId`)) {
        self$`observationVariableDbId` <- ObservationSummaryObject$`observationVariableDbId`
      }
      if (!is.null(ObservationSummaryObject$`observationVariableName`)) {
        self$`observationVariableName` <- ObservationSummaryObject$`observationVariableName`
      }
      if (!is.null(ObservationSummaryObject$`season`)) {
        seasonObject <- Season$new()
        seasonObject$fromJSON(jsonlite::toJSON(ObservationSummaryObject$season, auto_unbox = TRUE, null = "null"))
        self$`season` <- seasonObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "collector": %s,
           "observationDbId": %s,
           "observationTimeStamp": %s,
           "observationVariableDbId": %s,
           "observationVariableName": %s,
           "season": %s
        }',
        ifelse(is.null(self$`collector`), "null",jsonlite::toJSON(self$`collector`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`observationDbId`), "null",jsonlite::toJSON(self$`observationDbId`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`observationTimeStamp`), "null",jsonlite::toJSON(self$`observationTimeStamp`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`observationVariableDbId`), "null",jsonlite::toJSON(self$`observationVariableDbId`,auto_unbox=TRUE, null = "null")),
        ifelse(is.null(self$`observationVariableName`), "null",jsonlite::toJSON(self$`observationVariableName`,auto_unbox=TRUE, null = "null")),
        jsonlite::toJSON(self$`season`$toJSON(),auto_unbox=TRUE, null = "null")
      )
    },
    fromJSONString = function(ObservationSummaryJson) {
      ObservationSummaryObject <- jsonlite::fromJSON(ObservationSummaryJson)
      self$`collector` <- ObservationSummaryObject$`collector`
      self$`observationDbId` <- ObservationSummaryObject$`observationDbId`
      self$`observationTimeStamp` <- ObservationSummaryObject$`observationTimeStamp`
      self$`observationVariableDbId` <- ObservationSummaryObject$`observationVariableDbId`
      self$`observationVariableName` <- ObservationSummaryObject$`observationVariableName`
      SeasonObject <- Season$new()
      self$`season` <- SeasonObject$fromJSON(jsonlite::toJSON(ObservationSummaryObject$season, auto_unbox = TRUE))
    }
  )
)
