# OpenSilex API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: INSTANCE-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PaginationDTO Class
#'
#' @field pageSize 
#' @field currentPage 
#' @field totalCount 
#' @field totalPages 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PaginationDTO <- R6::R6Class(
  'PaginationDTO',
  public = list(
    `pageSize` = NULL,
    `currentPage` = NULL,
    `totalCount` = NULL,
    `totalPages` = NULL,
    initialize = function(`pageSize`, `currentPage`, `totalCount`, `totalPages`){
      if (!missing(`pageSize`)) {
        stopifnot(is.numeric(`pageSize`), length(`pageSize`) == 1)
        self$`pageSize` <- `pageSize`
      }
      if (!missing(`currentPage`)) {
        stopifnot(is.numeric(`currentPage`), length(`currentPage`) == 1)
        self$`currentPage` <- `currentPage`
      }
      if (!missing(`totalCount`)) {
        stopifnot(is.numeric(`totalCount`), length(`totalCount`) == 1)
        self$`totalCount` <- `totalCount`
      }
      if (!missing(`totalPages`)) {
        stopifnot(is.numeric(`totalPages`), length(`totalPages`) == 1)
        self$`totalPages` <- `totalPages`
      }
    },
    toJSON = function() {
      PaginationDTOObject <- list()
      if (!is.null(self$`pageSize`)) {
        PaginationDTOObject[['pageSize']] <- self$`pageSize`
      }
      if (!is.null(self$`currentPage`)) {
        PaginationDTOObject[['currentPage']] <- self$`currentPage`
      }
      if (!is.null(self$`totalCount`)) {
        PaginationDTOObject[['totalCount']] <- self$`totalCount`
      }
      if (!is.null(self$`totalPages`)) {
        PaginationDTOObject[['totalPages']] <- self$`totalPages`
      }

      PaginationDTOObject
    },
    fromJSON = function(PaginationDTOJson) {
      PaginationDTOObject <- jsonlite::fromJSON(PaginationDTOJson)
      if (!is.null(PaginationDTOObject$`pageSize`)) {
        self$`pageSize` <- PaginationDTOObject$`pageSize`
      }
      if (!is.null(PaginationDTOObject$`currentPage`)) {
        self$`currentPage` <- PaginationDTOObject$`currentPage`
      }
      if (!is.null(PaginationDTOObject$`totalCount`)) {
        self$`totalCount` <- PaginationDTOObject$`totalCount`
      }
      if (!is.null(PaginationDTOObject$`totalPages`)) {
        self$`totalPages` <- PaginationDTOObject$`totalPages`
      }
    },
    fromJSONObject = function(PaginationDTOObject) {
      if (!is.null(PaginationDTOObject$`pageSize`)) {
        self$`pageSize` <- PaginationDTOObject$`pageSize`
      }
      if (!is.null(PaginationDTOObject$`currentPage`)) {
        self$`currentPage` <- PaginationDTOObject$`currentPage`
      }
      if (!is.null(PaginationDTOObject$`totalCount`)) {
        self$`totalCount` <- PaginationDTOObject$`totalCount`
      }
      if (!is.null(PaginationDTOObject$`totalPages`)) {
        self$`totalPages` <- PaginationDTOObject$`totalPages`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "pageSize": %s,
           "currentPage": %s,
           "totalCount": %s,
           "totalPages": %s
        }',
        ifelse(is.null(self$`pageSize`), "null",as.numeric(jsonlite::toJSON(self$`pageSize`,auto_unbox=TRUE, null = "null"))),
        ifelse(is.null(self$`currentPage`), "null",as.numeric(jsonlite::toJSON(self$`currentPage`,auto_unbox=TRUE, null = "null"))),
        ifelse(is.null(self$`totalCount`), "null",as.numeric(jsonlite::toJSON(self$`totalCount`,auto_unbox=TRUE, null = "null"))),
        ifelse(is.null(self$`totalPages`), "null",as.numeric(jsonlite::toJSON(self$`totalPages`,auto_unbox=TRUE, null = "null")))
      )
    },
    fromJSONString = function(PaginationDTOJson) {
      PaginationDTOObject <- jsonlite::fromJSON(PaginationDTOJson)
      self$`pageSize` <- PaginationDTOObject$`pageSize`
      self$`currentPage` <- PaginationDTOObject$`currentPage`
      self$`totalCount` <- PaginationDTOObject$`totalCount`
      self$`totalPages` <- PaginationDTOObject$`totalPages`
    }
  )
)
